### PR TITLE
Bump Smack to 4.4

### PR DESCRIPTION
**Pull request by Flowdalic**

### CODE REVIEW

**Comment by wrooot** [comment]
I see you have removed WIP from the name. Should i merge it now?

**Comment by Flowdalic** [comment]
I've removed the draft state because it now compiles. As you may expect, it is not very thoroughly tested, though. I can not predict the fallout that a major Smack upgrade in Spark may produces. That is why I suggested creating a stable Spark '3.0' branch where the previous Smack version 4.3 is used. I don't think that you want to deliver Spark 3.0.1 with a major Smack bump.

Eventually, I would, as we have done with previous Smack upgrades, merge this into master, otherwise we will never be able to tell the amount of fallout that this upgrades brings.

**Comment by Plyha** [comment]
Hi, thank you for updating Smack in Spark. I can test this change in my company.

**Comment by wrooot** [comment]
I am trying out your smack-4.4 branch (that his PR is based of) and it seems to work ok. The only issue i have is that it fails to accept a self-signed certificate. Shows the Cannot verify certificate error:

org.jivesoftware.smack.SmackException$SmackWrappedException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.jivesoftware.smack.AbstractXMPPConnection.setCurrentConnectionExceptionAndNotify(AbstractXMPPConnection.java:690)
	at org.jivesoftware.smack.AbstractXMPPConnection.notifyConnectionError(AbstractXMPPConnection.java:994)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$4100(XMPPTCPConnection.java:130)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1164)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$700(XMPPTCPConnection.java:913)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:936)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:377)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:152)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1383)
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1291)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:435)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(XMPPTCPConnection.java:730)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1400(XMPPTCPConnection.java:130)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:987)
	... 3 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:456)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:323)
	at sun.security.validator.Validator.validate(Validator.java:271)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:315)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:223)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
	... 16 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:451)
	... 22 more

**Comment by Plyha** [comment]
Can you share the files with me?  I'd also like to check out Spark's work.

**Comment by Flowdalic** [comment]
> Can you share the files with me? I'd also like to check Spark's work.

You can run Spark directly from sources (at least in the smack-4.4 branch) using
```
git checkout smack-4.4
mvn java:exec
```

**Comment by wrooot** [comment]
Yeah, i also run it from source, so i don't have files for you. I have forked Flow's Spark repo on Github and added it to IntelliJ IDEA as a project (also have Git installed and AdoptOpenJDK 8). Then i changed to smack-4.4 branch and run the core/src/main/java/org/jivesoftware/launcher/Startup.java. Or you can have just Git and Maven installed and use those cmd commands Flow shared.

**Comment by Plyha** [comment]
[errors.txt](https://github.com/igniterealtime/Spark/files/6489705/errors.txt)



Thanks for the advice.
I built the project using maven and replaced the files in ProgramFiles, but I cannot connect to my Openfire server.
I also ran the Spark source code using IJ, but I also couldn't connect to my Openfire server.

**Comment by wrooot** [comment]
You might have missed some of the files or some older files interfere. What if you run it from the source code directly? I am able to login to igniterealtime.org and chat.

**Comment by Plyha** [comment]
I deleted the old files from the folder. Maybe the problem is that I connect via VPN to my Openfire server. Kstiti noticed that if I choose Java 11 in IJ, the translation becomes unreadable, but I think this is a different bug.

**Comment by Plyha** [comment]
I tried running Spark from IJ, and it takes a long time to connect to the server and I get an error like in the screenshot above.

**Comment by wrooot** [comment]
> By the way, I noticed that if I choose Java 11 in IJ(except for English), the translation becomes unreadable, but I think this is a different bug.

Yes, this is because of a workaround we made to make translations work with Java 8. https://igniterealtime.atlassian.net/browse/SPARK-2128

**Comment by Plyha** [comment]
I found the reason why I could not connect. This is due to Openfire 4.5.4. I can connect to my Openfire 4.6.3 test server but cannot connect to Openfire 4.5.4. Wroot, can you try connecting to the Openfire 4.5.X server too?

**Comment by wrooot** [comment]
I don't have a public server with that version and not a self signed certificate to connect to.

**Comment by Plyha** [comment]
I removed the self-signed certificate from my Openfire 4.5.4 server and still can't connect to it.
I was able to connect to my Openfire 4.6.3 without a self-signed certificate, with a self-signed certificate, with an external .RU certificate.
From this I can conclude that everything works fine for Openfire 4.6.3 and does not work for Openfire 4.5.4.
I hope only I have this problem, otherwise many users of Openfire 4.5.X and less will not be able to connect using Spark 3.0.0

**Comment by Plyha** [comment]
I wanted to see what is happening in the debug, but it seems that the debug is not working
image

**Comment by Plyha** [comment]
Here is the proof that in Openfire 4.6.3 I can connect and in 4.5.4 I can't.
https://youtu.be/z3-1nNXDvZ0

**Comment by Plyha** [comment]
I also ran into the problem that I cannot connect to my server if I use a self-signed certificate in Openfire.
`org.jivesoftware.smack.SmackException$SmackWrappedException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.jivesoftware.smack.AbstractXMPPConnection.setCurrentConnectionExceptionAndNotify(AbstractXMPPConnection.java:690)
	at org.jivesoftware.smack.AbstractXMPPConnection.notifyConnectionError(AbstractXMPPConnection.java:994)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$4100(XMPPTCPConnection.java:130)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1164)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$700(XMPPTCPConnection.java:913)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:936)
	at java.lang.Thread.run(Unknown Source)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
	at sun.security.ssl.Handshaker.process_record(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(XMPPTCPConnection.java:730)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1400(XMPPTCPConnection.java:130)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:987)
	... 3 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at sun.security.validator.Validator.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 14 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.security.cert.CertPathBuilder.build(Unknown Source)
	... 20 more
`

>The only issue i have is that it fails to accept a self-signed certificate. Shows the Cannot verify certificate error:
> 
> org.jivesoftware.smack.SmackException$SmackWrappedException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> at org.jivesoftware.smack.AbstractXMPPConnection.setCurrentConnectionExceptionAndNotify(AbstractXMPPConnection.java:690)
> at org.jivesoftware.smack.AbstractXMPPConnection.notifyConnectionError(AbstractXMPPConnection.java:994)
> at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$4100(XMPPTCPConnection.java:130)
> at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1164)
> at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$700(XMPPTCPConnection.java:913)
> at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:936)
> at java.lang.Thread.run(Thread.java:748)
> Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> at sun.security.ssl.Alert.createSSLException(Alert.java:131)
> at sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
> at sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
> at sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
> at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
> at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
> at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
> at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:377)
> at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
> at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
> at sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
> at sun.security.ssl.SSLTransport.decode(SSLTransport.java:152)
> at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1383)
> at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1291)
> at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:435)
> at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(XMPPTCPConnection.java:730)
> at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1400(XMPPTCPConnection.java:130)
> at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:987)
> ... 3 more
> Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:456)
> at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:323)
> at sun.security.validator.Validator.validate(Validator.java:271)
> at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:315)
> at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:223)
> at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
> at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
> ... 16 more
> Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
> at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
> at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
> at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:451)
> ... 22 more

**Comment by guusdk** [comment]
> I wanted to see what is happening in the debug, but it seems that the debug is not working
> image

The issue with the debugger is caused by a bug in Smack (SMACK-908) that is being exposed by a change in Spark's decoration of UI elements. See https://discourse.igniterealtime.org/t/cant-use-debugger-with-spark-3-0-0-beta/ for details. Tracking for Spark as https://igniterealtime.atlassian.net/browse/SPARK-2232

**Comment by guusdk** [comment]
Connectivity issues (Spark not accepting a self-signed certificate even though it's configured to accept these) might be caused by https://discourse.igniterealtime.org/t/should-default-trustmanagers-be-based-on-sslcontext/

**Comment by guusdk** [comment]
I've provided a work-around in https://github.com/igniterealtime/Spark/pull/623/commits/6bb652847aba902e6ac3586fb53cce5966f33579 - but I wonder if this should be needed.

With these changes, You can authenticate on Openfire 4.5.2 (also on a later version), but you still can't fully log in to Openfire 4.5.2. I suspect that this relates to Smack becoming more strict in parsing stanzas, which causes it to discard a service discovery reply - which is needed to complete the logging in processes.

```
Jul 08, 2021 12:12:51 PM org.jivesoftware.smack.parsing.ExceptionLoggingCallback handleUnparsableStanza
SEVERE: Smack message parsing exception. Content: '</field></x></query></iq>'
org.jivesoftware.smack.parsing.SmackParsingException: text-single fields can have at most one value, this one had 2
	at org.jivesoftware.smackx.xdata.provider.DataFormProvider.ensureAtMostSingleValue(DataFormProvider.java:415)
	at org.jivesoftware.smackx.xdata.provider.DataFormProvider.parseSingleKindFormField(DataFormProvider.java:313)
	at org.jivesoftware.smackx.xdata.provider.DataFormProvider.parseField(DataFormProvider.java:272)
	at org.jivesoftware.smackx.xdata.provider.DataFormProvider.parseField(DataFormProvider.java:143)
	at org.jivesoftware.smackx.xdata.provider.DataFormProvider.parse(DataFormProvider.java:91)
	at org.jivesoftware.smackx.xdata.provider.DataFormProvider.parse(DataFormProvider.java:60)
	at org.jivesoftware.smack.provider.Provider.parse(Provider.java:53)
	at org.jivesoftware.smack.util.PacketParserUtils.parseExtensionElement(PacketParserUtils.java:834)
	at org.jivesoftware.smack.util.PacketParserUtils.addExtensionElement(PacketParserUtils.java:910)
	at org.jivesoftware.smack.util.PacketParserUtils.addExtensionElement(PacketParserUtils.java:905)
	at org.jivesoftware.smackx.disco.provider.DiscoverInfoProvider.parse(DiscoverInfoProvider.java:72)
	at org.jivesoftware.smackx.disco.provider.DiscoverInfoProvider.parse(DiscoverInfoProvider.java:39)
	at org.jivesoftware.smack.provider.IqProvider.parse(IqProvider.java:40)
	at org.jivesoftware.smack.util.PacketParserUtils.parseIQ(PacketParserUtils.java:549)
	at org.jivesoftware.smack.util.PacketParserUtils.parseStanza(PacketParserUtils.java:113)
	at org.jivesoftware.smack.AbstractXMPPConnection.parseAndProcessStanza(AbstractXMPPConnection.java:1448)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1000(XMPPTCPConnection.java:130)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:969)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$700(XMPPTCPConnection.java:913)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:936)
	at java.lang.Thread.run(Thread.java:748)
```

Even though the problem with Openfire sending invalid data has been fixed in later releases, it will exist in many of our existing installations. If we can't disable the new strictness in Smack, I think upgrading to Smack 4.4 is not something we should do in the next few ... years? For as long as older versions of Openfire are around. Given that I'm frequently talking to people running a version that's a couple of years old ...

**Comment by guusdk** [comment]
With the state of the [current smack-4.4 branch](https://github.com/igniterealtime/Spark/pull/623/commits/04859eb833c3f184c24c5597e34a788c557d02d7) from Flow, I'm seeing two things that might be unrelated, that do not occur with the version of the code that I had been using before (which is commit 8fcb9657880230fcb872aed8825c41b4cfa48365):

1. After I log in, the UI becomes completely unresponsive. My client does automatically join a bookmarked MUC and I see history in that room, but I can't interact with the UI whatsoever (is this a regression of [SPARK-2234](https://igniterealtime.atlassian.net/browse/SPARK-2234) perhaps?)
2. After logging in, I'm seeing numerous warnings like this one:
```
WARNING: Failed to parse extension element in Presence stanza: PresenceBuilder(id='3CKfX-105' from='SOMEONE@igniterealtime.org' to='HIDDEN@igniterealtime.org/octarine' language='en-US' type='unavailable' Extension Elements[{vcard-temp:x:update}x])
java.lang.IllegalStateException: Illegal to call getName() when event type is CHARACTERS. Valid states are START_ELEMENT, END_ELEMENT
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.getName(XMLStreamReaderImpl.java:938)
	at org.jivesoftware.smack.xml.stax.StaxXmlPullParser.getQName(StaxXmlPullParser.java:123)
	at org.jivesoftware.smack.xml.stax.StaxXmlPullParser.getName(StaxXmlPullParser.java:117)
	at org.jivesoftware.sparkimpl.profile.ext.JabberAvatarExtension$Provider.parse(JabberAvatarExtension.java:69)
	at org.jivesoftware.sparkimpl.profile.ext.JabberAvatarExtension$Provider.parse(JabberAvatarExtension.java:56)
	at org.jivesoftware.smack.provider.Provider.parse(Provider.java:53)
	at org.jivesoftware.smack.util.PacketParserUtils.parseExtensionElement(PacketParserUtils.java:834)
	at org.jivesoftware.smack.util.PacketParserUtils.parsePresence(PacketParserUtils.java:477)
	at org.jivesoftware.smack.util.PacketParserUtils.parseStanza(PacketParserUtils.java:115)
	at org.jivesoftware.smack.AbstractXMPPConnection.parseAndProcessStanza(AbstractXMPPConnection.java:1457)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1000(XMPPTCPConnection.java:130)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:969)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$700(XMPPTCPConnection.java:913)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:936)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Flowdalic** [comment]
2. should be fixed https://github.com/igniterealtime/Spark/pull/623/commits/918b8c51210f548a367ba4947190f41e8d2bab65.

**Comment by guusdk** [comment]
That was fast. :)

This fixes some, but not all occurrences, I think. Could it be that a similar fix is needed in more places?

I'm also seeing this in `VCardUpdateExtension` - and I guess that might mean that other code also have this issue?
```
WARNING: Failed to parse extension element in Presence stanza: PresenceBuilder(from='REDACTED@jabber.org/Ψ+' to='HIDDEN@igniterealtime.org' language='en-US' type='available' mode='away' priority='127' Extension Elements[{http://jabber.org/protocol/caps}c])
java.lang.IllegalStateException: Illegal to call getName() when event type is CHARACTERS. Valid states are START_ELEMENT, END_ELEMENT
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.getName(XMLStreamReaderImpl.java:938)
	at org.jivesoftware.smack.xml.stax.StaxXmlPullParser.getQName(StaxXmlPullParser.java:123)
	at org.jivesoftware.smack.xml.stax.StaxXmlPullParser.getName(StaxXmlPullParser.java:117)
	at org.jivesoftware.sparkimpl.profile.ext.VCardUpdateExtension$Provider.parse(VCardUpdateExtension.java:75)
	at org.jivesoftware.sparkimpl.profile.ext.VCardUpdateExtension$Provider.parse(VCardUpdateExtension.java:62)
	at org.jivesoftware.smack.provider.Provider.parse(Provider.java:53)
	at org.jivesoftware.smack.util.PacketParserUtils.parseExtensionElement(PacketParserUtils.java:834)
	at org.jivesoftware.smack.util.PacketParserUtils.parsePresence(PacketParserUtils.java:477)
	at org.jivesoftware.smack.util.PacketParserUtils.parseStanza(PacketParserUtils.java:115)
	at org.jivesoftware.smack.AbstractXMPPConnection.parseAndProcessStanza(AbstractXMPPConnection.java:1457)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1000(XMPPTCPConnection.java:130)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:969)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$700(XMPPTCPConnection.java:913)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:936)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Plyha** [comment]
Oops!
I tested your latest changes and accidentally created my commits, now I will try to remove them.

**Comment by Flowdalic** [comment]
> I tested your latest changes and accidentally created my commits, now I will try to remove them.

`git push -f flow  918b8c5:smack-4.4` would reset the PR's source branch to a known good state.

**Comment by Flowdalic** [comment]
Reverting a commit is not what you want to do in this case. I am resetting the source branch.

**Comment by Plyha** [comment]
thank you, sorry for my mistake.

**Comment by Plyha** [comment]
can we merge this commit and release Spark 3.0 beta2?  otherwise we will not know how smack 4.4 affects spark;)

**Comment by Plyha** [comment]
Due to the fact that now many administrators will update their Openfire servers to the 4.6.x branch, I suggest merging Smack 4.4.x into Spark 3.0.0.

**Pull request merged**
