### PR TITLE
SPARK-1613: Force wrapping of long lines.

### PR DESCRIPTION
**Pull request by guusdk**

### CODE REVIEW

**Comment by wrooot** [comment]
You are our hero! :+1: Although, i would prefer for it to cut on the border of the window instead of going to the next line for the whole long line, but as it would most often happen with URLs, it's a minor thing and is for sure much much better than a vertical scroll :)

**Comment by guusdk** [comment]
Yeah - I'm not a real expert in these UI things. Best effort, couldn't get it prettier :)

**Comment by nokaoii** [comment]
Thank you! You're awesome guusdk!

**Comment by wrooot** [comment]
There is a little regression uncovered by speedy. The messages don't come through on a fresh profile.

**Pull request merged**
