### PR TITLE
GUI Update

### PR DESCRIPTION
**Pull request by k33ptoo**
This is a general update for GUI - Update is as follows
* Update List of themes to just 1 [Custom SparkLightLaf from FlatLightLAF]
* Update All Visible Icons to Material Outline
* Update Login Page - Use Login Panel instead
* Update Preference Window UI
* Update Mainwindow Size

### CODE REVIEW

**Comment by speedy01** [comment]
@k33ptoo Thanks you!

**Comment by k33ptoo** [comment]
Welcome.

**Comment by wrooot** [comment]
Thanks :)

**Comment by speedy01** [comment]
@wrooot perhaps we should provide @k33ptoo access to atlassian as well.  @k33ptoo looking forward your continued progress!  You have no idea how much the community appreciates your contribution!

**Comment by wrooot** [comment]
I believe our Jira is using Atlassian crowd. If Amos has an Atlassian account, we can add it to a group which has access to Spark project. We also have a Discourse forum and i have posted yesterday for people to test and provide feedback https://discourse.igniterealtime.org/t/spark-look-and-feel-refresh/89340

**Pull request merged**
