### PR TITLE
mac installer improvements

### PR DESCRIPTION
**Pull request by speedy01**
Apple appears to be dropping its version of java, and doesn't have any plans to update past 1.6. This should allow for oracle java to be used for spark.  This replacesthe forked apple jarbundler in favor a fork version of oracle appbundler.

### CODE REVIEW

**Comment by wrooot** [comment]
The Mac build is failing:
BUILD FAILED
/Users/j2ee-bamboo/bamboo-agent-home/xml-data/build-dir/SPARK-NIGHTLYMAC-JOB1/build/build.xml:718: java.lang.UnsupportedClassVersionError: com/oracle/appbundler/AppBundlerTask : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
        at org.apache.tools.ant.AntClassLoader.defineClassFromData(AntClassLoader.java:1136)
        at org.apache.tools.ant.AntClassLoader.getClassFromStream(AntClassLoader.java:1307)
        at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1362)
        at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1323)
        at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1076)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:266)
        at org.apache.tools.ant.taskdefs.Definer.addDefinition(Definer.java:579)
        at org.apache.tools.ant.taskdefs.Definer.execute(Definer.java:237)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.Main.runBuild(Main.java:851)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

**Comment by akrherz** [comment]
I updated the bamboo job to use JRE 1.8

**Comment by wrooot** [comment]
Still fails though.

**Comment by speedy01** [comment]
things building fine for me..go figure!  I might have a left over lib lingering somewhere that's getting picked up.  Hope to have an answer and solution shortly! :)

**Comment by speedy01** [comment]
I think this can be resolved in two ways. The missing symbols are included in the oracle jdk in rt.jar. By added the compiler argument -DXignore.symbol.file to the apple plugin build, everything compiles.  
Another option is to include AppleJavaExtensions.jar lib.   It looks like Apple hasn't updated AppleJavaExtensions.jar in a few years, with the last version being 1.6 in 2011
https://developer.apple.com/legacy/library/samplecode/AppleJavaExtensions/Introduction/Intro.html

Info on the compiler switch
https://github.com/mcourteaux/MultiTouch-Gestures-Java
https://stackoverflow.com/questions/4065401/using-internal-sun-classes-with-javac

I've tested both, and they both seem to yield the same results. Feedback welcome!

**Comment by wrooot** [comment]
Well, if we must choose, i would go with the first option (compiler switch) instead of using outdated jar.

**Pull request merged**
