### PR TITLE
SPARK-1852: Add anonymous SASL login support

### PR DESCRIPTION
**Pull request by volatilevar**
- Add a "login anonymously" checkbox to the login dialog
- Support anonymous login using Smack
- Minor format/typo fixes

### CODE REVIEW

**Comment by wrooot** [comment]
I see that you have already added the default properties. Nice ;)

**Comment by wrooot** [comment]
There is one problem though. The checkbox is only shown first time. Once its value is written into spark.properties file (either true or false) it is not shown on the Login screen and even deleting it from the file is not helping for some reason.

**Comment by volatilevar** [comment]
Thanks for merging my changes in.

I tried but could not reproduce this problem by editing the "ccAnonymouslogin" key in spark.properties. When ccAnonymousLogin is set to true, I can always see the checkbox when Spark launches. Could you please let me know the steps you followed?

**Comment by wrooot** [comment]
I understand what's happening. You've already built in support for Client Control plugin for this checkbox. But the plugin itself hasn't been updated yet, so it returns false by default (actually nothing and it is considered as boolean false). I have already contacted the person who did recent changes to that plugin. Or i will do the update myself as it seems like a simple addition.

Thanks again ;)

**Comment by volatilevar** [comment]
Glad that you found the cause. Thanks!

**Pull request merged**
