### PR TITLE
 Replace old emoticons with Twemoji emoticons

### PR DESCRIPTION
**Pull request by Plyha**
This emoji from https://github.com/twitter/twemoji

https://discourse.igniterealtime.org/t/new-emoji-for-new-spark/89696/19?u=ilyahlevnoy

### CODE REVIEW

**Comment by wrooot** [comment]
Guus is ok with this. So i will merge this and add attribution line to the Readme myself. Thanks.

**Comment by Plyha** [comment]
Thank you!)

**Pull request merged**
