### PR TITLE
SPARK-1457 Update Translator plugin

### PR DESCRIPTION
**Pull request by Plyha**

### CODE REVIEW

**Comment by Plyha** [comment]
The plugin broke many years ago. I think we need to change the API. I found a free API - https://libretranslate.com/ . Unfortunately Google translate and other APIs are paid or require an account.

**Comment by guusdk** [comment]
The old plugin is working fine for me, it appears.

**Comment by Plyha** [comment]
Strange, the old plugin doesn't work for me. At least due to the fact that the plugin uses http and not https. I also get these exceptions.

dec 22, 2022 8:00:03 PM org.jivesoftware.spark.util.log.Log error
SEVERE: A ChatRoomListener (org.jivesoftware.spark.translator.TranslatorPlugin$1@18fa300) threw an exception while processing a 'opened' event for room: org.jivesoftware.spark.ui.rooms.ChatRoomImpl[,0,0,860x296,invalid,layout=java.awt.GridBagLayout,alignmentX=0.0,alignmentY=0.0,border=javax.swing.border.MatteBorder@14ca5c9,flags=9,maximumSize=,minimumSize=,preferredSize=]
java.lang.IllegalArgumentException: Cannot store java.lang.Object in an array of java.lang.String
	at org.apache.commons.lang3.ArrayUtils.addAll(ArrayUtils.java:1081)
	at org.jivesoftware.spark.translator.TranslatorUtil.getLanguage(TranslatorUtil.java:45)
	at org.jivesoftware.spark.translator.TranslatorPlugin$1.chatRoomOpened(TranslatorPlugin.java:55)
	at org.jivesoftware.spark.ui.ChatContainer.fireChatRoomOpened(ChatContainer.java:895)
	at org.jivesoftware.spark.ui.ChatContainer.addChatRoom(ChatContainer.java:329)
	at org.jivesoftware.spark.ChatManager$1.finished(ChatManager.java:334)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.ArrayStoreException
	at java.lang.System.arraycopy(Native Method)
	at org.apache.commons.lang3.ArrayUtils.addAll(ArrayUtils.java:1070)
	... 19 more

dec 24, 2022 9:03:28 PM org.jivesoftware.spark.util.log.Log error
SEVERE: A MessageEventListener ('org.jivesoftware.spark.translator.TranslatorPlugin$1$1@1ce1f93') threw an exception while processing an outgoing message (to 'testuser@ansible.lan').
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(Unknown Source)
	at org.jivesoftware.spark.translator.TranslatorPlugin$1$1.sendingMessage(TranslatorPlugin.java:74)
	at org.jivesoftware.spark.ui.rooms.ChatRoomImpl.fireOutgoingMessageSending(ChatRoomImpl.java:660)
	at org.jivesoftware.spark.ui.rooms.ChatRoomImpl.sendMessage(ChatRoomImpl.java:314)
	at org.jivesoftware.spark.ui.rooms.ChatRoomImpl.sendMessage(ChatRoomImpl.java:286)
	at org.jivesoftware.spark.ui.rooms.ChatRoomImpl.sendMessage(ChatRoomImpl.java:252)
	at org.jivesoftware.spark.ui.ChatRoom.checkForEnter(ChatRoom.java:659)
	at org.jivesoftware.spark.ui.ChatRoom.access$300(ChatRoom.java:62)
	at org.jivesoftware.spark.ui.ChatRoom$3.keyPressed(ChatRoom.java:268)
	at java.awt.AWTEventMulticaster.keyPressed(Unknown Source)
	at java.awt.Component.processKeyEvent(Unknown Source)
	at javax.swing.JComponent.processKeyEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by Plyha** [comment]
Some screenshots of the updated Translator plugin
image
image
image
image

**Pull request merged**
