### PR TITLE
Add TranscriptWindowTextProcesser

### PR DESCRIPTION
**Pull request by bonashen**
Add TranscriptWindowTextProcesser,let's develope plugin process TranscriptWindow text.

### CODE REVIEW

**Comment by wrooot** [comment]
Hi. Sorry for late reply (stuck in the hospital..). I'm not a developer, so can you explain in general what you patch adds to Spark?  How will it back nefit other users or is more for you personal needs? Will it affect current Spark behavior? Also is it a normal practice to use .* wildcards in imports? 

I will have to file a ticket in the bug tracker for your patch after you explain it.

**Comment by wrooot** [comment]
Anything to reply?

**Comment by marclaporte** [comment]
@bonashen  We really want you to get involved more!

**Comment by wrooot** [comment]
Closing as no further feedback received and it already conflicts with the current code.

**Pull request closed without merging**
