### PR TITLE
Fix typos and refactor duplicated property in i18n resources

### PR DESCRIPTION
**Pull request by R87A**
Fix typos in identifiers and duplicated property in internationalization resources by refactor. Also remove some trailing spaces.
_p.s. This is my first contribution to a project on GitHub, so I decided to start with less significant and more fail safe things than I wanted to. If this will take success then I would like to contribute much more to this project._

### CODE REVIEW

**Comment by wrooot** [comment]
Thanks! I have created https://issues.igniterealtime.org/browse/SPARK-2165 for this. If you have account in our JIRA, i can assign it as completed by you. Looking forward to more patches ;)

**Comment by akrherz** [comment]
Hi @R87A, thank you so much for your contribution.  We are very happy to have new contributors to Spark!

**Comment by R87A** [comment]
> Thanks! I have created https://issues.igniterealtime.org/browse/SPARK-2165 for this. If you have account in our JIRA, i can assign it as completed by you. Looking forward to more patches ;)
I have created an account on Spark's JIRA - "R87A".

**Comment by wrooot** [comment]
I have assigned you to spark-developers group in Jira and assigned this ticket to you ;)

**Pull request merged**
