### PR TITLE
Updated italian translation

### PR DESCRIPTION
**Pull request by nicoben**
Update Italian translation

### CODE REVIEW

**Comment by guusdk** [comment]
Something went wrong here: pretty much all files are modified. That cannot be right.

**Comment by wrooot** [comment]
Yeah, i was going to cherry pick the actual translation changes :)

**Comment by nicoben** [comment]
I must have messed up somenthing, I'll check it again.
Sorry.

2016-05-10 18:32 GMT+02:00 wroot <notifications@github.com>:

**Comment by nicoben** [comment]
Could you take only d2af873, 7e6760a, 73e69cc commits ?

**Comment by wrooot** [comment]
I would. Bu manually in my own commit (copy paste). I'm not very verse with git and i don't see an option to do this on Github (via web client).

**Comment by wrooot** [comment]
Merged as https://github.com/igniterealtime/Spark/pull/156

**Pull request closed without merging**
