### PR TITLE
Spark LookAndFeel

### PR DESCRIPTION
**Pull request by freeseawind**
Hello  ,

I am spark loyal users.

Lately,I wrote a Java Swing LookAndFeel. I think it's cool.

I would like to contribute to the code. I wish it could be used for spark.

To see the littleluck LookAndFeel, visit https://github.com/freeseawind/littleluck.

### CODE REVIEW

**Comment by guusdk** [comment]
Thank you for your contribution! It is hard to evaluate this pull request, for several reasons. Could you please address these:

- Please do not modify every line of an entire file (such as src/java/org/jivesoftware/spark/ui/themes/ThemePanel.java), but only apply changes to lines that need changes. That way, we can evaluate what the differences are.
- I noticed that you included several jar files (libraries), but also Java files, which both appear to be the generic look-and-feel implementation. When files are not specific to Spark, I prefer those files to be added as a library. This way, the look-and-feel implementation will be used by Spark, instead of be "part of" Spark. I rather not need to maintain the look-and-feel implementation itself, just the Spark implementation.
- I'm happy to see that you documented the code. My Chinese is a bit rusty thought. :) Could you please write your comments in English instead of Chinese?
- Is it possible to make this a plugin?

If you make these changes, it will be a lot easier.

I did try to use your changes, but right after I selected the "luckmetal" look and feel, I got this stack trace:
```
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
        at freeseawind.lf.cfg.LuckResourceBundle.getIconRes(Unknown Source)
        at freeseawind.lf.cfg.LuckGlobalBundle.loadImages(Unknown Source)
        at freeseawind.lf.cfg.LuckResourceBundle.installDefaults(Unknown Source)
        at freeseawind.lf.cfg.LuckResConfigImpl.loadResources(Unknown Source)
        at freeseawind.lf.LuckMetalLookAndFeel.initComponentDefaults(Unknown Source)
        at javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:148)
        at javax.swing.plaf.metal.MetalLookAndFeel.getDefaults(MetalLookAndFeel.java:1577)
        at javax.swing.UIManager.setLookAndFeel(UIManager.java:539)
        at javax.swing.UIManager.setLookAndFeel(UIManager.java:583)
        at org.jivesoftware.spark.ui.themes.ThemePanel$1.setNewLaF(ThemePanel.java:259)
        at org.jivesoftware.spark.ui.themes.ThemePanel$1.finished(ThemePanel.java:288)
        at org.jivesoftware.spark.util.SwingWorker.lambda$null$0(SwingWorker.java:150)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.util.MissingResourceException: Can't find bundle for base name i18n/littleluck_i18n, locale en_US
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
        at freeseawind.lf.utils.LuckRes.<clinit>(Unknown Source)
        ... 26 more

```

**Comment by freeseawind** [comment]
https://github.com/freeseawind/littleluck/blob/master/README_en.md

**Comment by freeseawind** [comment]
yet, you must add littleluck.jar and ninepatch.jar to your classpath.

**Comment by wrooot** [comment]
freeseawind, Guus meant comments in the code itself. Although, as this is not the core part of Spark, maybe it is ok to have comments in Chinese there. But it would be hard for someone else to look through the code.

What is src/littleluck/resources/i18n/littleluck_i18n_zh_CN.properties for? Where in the GUI will it show this? Do we need other translations for this?

**Comment by freeseawind** [comment]
It's not needed at the moment.

**Comment by wrooot** [comment]
So, maybe you should remove it as you fix the other issues mentioned by Guus (themepanel, exception, etc.). I have filed this as https://issues.igniterealtime.org/browse/SPARK-1802 (notice, i have set it for 2.8.2 as i want 2.8.1 to be a fix release and don't want to introduce any big changes/features).

**Comment by freeseawind** [comment]
thank you, i will do it

**Pull request closed without merging**
