### PR TITLE
fix-logic-error-in-UserSearchResult-getFirstValue

### PR DESCRIPTION
**Pull request by dmitrii-88**

### CODE REVIEW

**Comment by wrooot** [comment]
Thanks for you patch. I have assigned @guusdk to check it. Seems good, but as i'm not a dev myself, it is better to check :)

**Comment by wrooot** [comment]
Thanks @Alameyo. Will merge it then.

**Comment by dmitrii-88** [comment]
Because of this error person search does not work.

**Comment by wrooot** [comment]
Could it also fix https://issues.igniterealtime.org/browse/SPARK-1873

**Comment by dmitrii-88** [comment]
Yes, it could.

**Comment by wrooot** [comment]
Will ask in the forums if someone can test it.

**Comment by wrooot** [comment]
So far one confirmation that search works again.

**Pull request merged**
