### PR TITLE
SPARK-2011 Bring back functionality for "Accept all" certificates

### PR DESCRIPTION
**Pull request by Alameyo**
Now again this will accept all certificates regardless of their validity or being a part of the TrustStores.

### CODE REVIEW

**Comment by guusdk** [comment]
Do we want to have this functionality? If we get a popup each time that we receive an untrusted certificate, then there is no much use for an "accept all" anymore.

**Comment by guusdk** [comment]
Do we want to have this functionality? If we get a popup each time that we receive an untrusted certificate, then there is no much use for an "accept all" anymore.

**Comment by Alameyo** [comment]
I think we can left this and still have popup. Just in case when this is ticked popup will not be shown, client will auto trust everything.

**Comment by guusdk** [comment]
From a security perspective, I dislike a "trust all" option. Users can easily forget that it is enabled. The popup offers the same feature, but on a per-certificate basis. I like that a lot better.

**Comment by wrooot** [comment]
Currently by default Accept all is disabled (in 2.8.3 fresh install). So, we can still have it, so it won't affect current installations and admins won't have to instruct their users suddenly (for a local server that's not a real issue).

**Comment by wrooot** [comment]
Wait, but there is already Accept all in the current builds. What does it do then? If we going to not bring back Accept all, then it should be removed from the Certificates tab as well.

**Comment by Alameyo** [comment]
Ok, I will remove that while adding popup.

**Pull request closed without merging**
