### PR TITLE
SPARK-1904: Various improvements to setting avatar

### PR DESCRIPTION
**Pull request by vipinraj**
- Disabled enlarging small images.
- Added warning messages for small images and non-square images.

### CODE REVIEW

**Comment by wrooot** [comment]
Waiting for @guusdk to review.

**Comment by guusdk** [comment]
Oh, my bad. I thought I had already merged this one before! Sorry for the delay!

**Comment by wrooot** [comment]
There is a side effect. The profile window is not closing after you press Save or Cancel in it. Actually it takes multiple presses of Save or Cancel to make it close.

**Comment by guusdk** [comment]
For the record: wroot created a new ticket for the side effect (which looks like a pre-existing condition): SPARK-1917

**Pull request merged**
