### PR TITLE
SPARK-1822 - Add additional default properties to control GUI settings

### PR DESCRIPTION
**Pull request by BittyByte**
Updated to include the following new settings in the _default.properties_ file:

_# If true, disable the option to transfer files_
**DISABLE_FILE_XFER = false**

_# If true, disable the option to remove contacts and groups in roster_
**DISABLE_REMOVALS = false**

_# If true, disable the option to rename contacts and groups in roster_
**DISABLE_RENAMES = false**

_# If true, disable the options to move and copy contacts_
**DISABLE_MOVE_AND_COPY = false**

_# If true, disable the option to edit the profile_
**DISABLE_EDIT_PROFILE = false**

_# If true, disable the "View notes" option under "Actions"_
**DISABLE_VIEW_NOTES = false**

_# If true, disable the "View task list" option under "Actions"_
**DISABLE_VIEW_TASK_LIST = false**

### CODE REVIEW

**Comment by wrooot** [comment]
I've been messing around with the code based on how you did DISABLE_EDIT_PROFILE trying to apply same logic to fix https://issues.igniterealtime.org/browse/SPARK-1516 but it is not as simple as adding another IF :) My dev skills are lacking to figure it out.

**Comment by BittyByte** [comment]
I’ll look into that later today and see if I can figure it out. However, my dev skills are also lacking. :-)

**Comment by BittyByte** [comment]
I assigned SPARK-1516 to myself and will work on it later today.

**Comment by wrooot** [comment]
Thanks

**Pull request merged**
