### PR TITLE
SPARK-1802: Add littleluck LaF skin

### PR DESCRIPTION
**Pull request by freeseawind**

### CODE REVIEW

**Comment by guusdk** [comment]
Actually, nevermind, we can do that in Github.

**Comment by freeseawind** [comment]
thanks a lot

**Comment by guusdk** [comment]
Thank you :)

**Comment by guusdk** [comment]
Actually: perhaps you'd be interested in fixing more issues in the code? This one, for instance, will probably be easier for you to work on than it is for us: https://issues.igniterealtime.org/browse/SPARK-1639

**Comment by wrooot** [comment]
Oh, Guus, you sneaky fox :) Yeah, there are some bugs that one can fix for us :) Btw, i have tried out this new skin. Everything looks fine. Just in the Chat window there is no hover effect for the buttons (profile, file transfer, emoticons, etc.).

**Comment by freeseawind** [comment]
I think the plugin is no load (profile, file transfer, emoticons, etc.).

**Comment by freeseawind** [comment]
LittleLuck Github-page：https://github.com/freeseawind/littleluck/blob/master/README_en.md

**Pull request merged**
