### PR TITLE
Fix certchain validation

### PR DESCRIPTION
**Pull request by guusdk**

### CODE REVIEW

**Comment by guusdk** [comment]
With this state, I'm still seeing issue SPARK-2187 which I'd like to fix before merging.

Also, with the improved checks, I'm now seeing validation failures caused by a certificate not providing OCSP data. When Spark is configured to verify OCSP, this now causes the validation to fail. I'm not sure if this is correct. Does that setting in Spark mean: "check if OCSP data provided by cert" or "Check OCSP, fail if no data provided" ?

**Comment by wrooot** [comment]
@Alameyo do you remember how it was setup? The OCSP check.

**Comment by guusdk** [comment]
It appears that the OCSP check failed because of a bug in our code (SPARK-2188). I've now fixed that.

I think this PR is now ready for a merge. There are still some minor issues, but what is in this PR should be a good improvement over what we had.

@wrooot I'd suggest to quickly build a version with this, and ask the usual suspects to do a round of testing with regards to different TLS scenarios.

**Comment by Alameyo** [comment]
Seems alright.

**Pull request merged**
