### PR TITLE
SPARK-1900 - Enable idle plugin and disable redundant external system tray plugin 

### PR DESCRIPTION
**Pull request by speedy01**

### CODE REVIEW

**Comment by wrooot** [comment]
Guus is too busy. Merging :)

**Comment by guusdk** [comment]
STOP MERGING THINGS ON YOUR BIRTHDAY!

**Comment by guusdk** [comment]
Also, can't we just delete this?

**Comment by speedy01** [comment]
I didn't see the external system tray plugin  in pre-maven builds..so I didn't know if it was an intended addition or not. I also didn't know if excluding the idle stuff was intentional or not.

**Comment by speedy01** [comment]
Happy birthday @wrooot !

**Comment by wrooot** [comment]
Filed a ticket for systemtray removal https://issues.igniterealtime.org/browse/SPARK-2020

**Pull request merged**
