### PR TITLE
SPARK-2167: Fix login dialog behavior.

### PR DESCRIPTION
**Pull request by R87A**
This fixes the behavior of the login dialog related to handling the default property "HOST_NAME_CHANGE_DISABLED".
It also includes some refactoring and code formatting improvements.

### CODE REVIEW

**Comment by akrherz** [comment]
Thanks for your contribution, but it is very difficult to review this code change since you intermix a whitespace commit and a functional change.  If you want to let your IDE / linter do its thing, please save that as a commit first and then do your functional change as another commit.

**Comment by wrooot** [comment]
I agree with akrherz. It will be hard to look for regressions later or just to create another PR by looking at this one as an example. Maybe you can redo this.

**Comment by R87A** [comment]
I got it, and I will consider this. Sorry for your wasted time.
Of course I'll try to redo this work.
I am new to GitHub so I really appreciate your advice.

**Comment by akrherz** [comment]
> Sorry for your wasted time.

No need to apologize!  Hopefully this does not discourage you.  One of the neat things about `git` is being able to make a lot of commits and then arbitrarily squash and/or rearrange them how you see fit at a later time.  Have an "atomic" mentality about fixing one thing, committing it, then fixing another, committing it, and so on.

**Comment by wrooot** [comment]
For sure, not a problem. It often happens when i submit a PR and later see an error or typo. I can just do new commit in my fork and it goes as a new commit to the existing PR automagically :)

**Pull request closed without merging**
