### PR TITLE
SPARK-2146: Bouncy Castle 1.65 instead of 1.57

### PR DESCRIPTION
**Pull request by Neustradamus**
Bouncy Castle 1.65 instead of 1.57: https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html

CVEs: https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

### CODE REVIEW

**Comment by wrooot** [comment]
@guusdk what do you think? Is it safe to just swap versions?

**Comment by guusdk** [comment]
Yes, should not be a problem. Just like with JREs, we should generally upgrade to the latest release prior to releasing Spark.

**Comment by wrooot** [comment]
Created https://issues.igniterealtime.org/browse/SPARK-2146

**Comment by Neustradamus** [comment]
@wrooot: Thanks for this merging and the 1.66 update in the same time:
- https://github.com/igniterealtime/Spark/commit/6b89d28ef7afc9aab5f1d489e1f9ac6e0d363177

**Pull request merged**
