### PR TITLE
Spark 1520

### PR DESCRIPTION
**Pull request by speedy01**

### CODE REVIEW

**Comment by wrooot** [comment]
Hm, maybe it wasn't my fault after all. Travis is failing on this. I think your PR is still somehow tied to that reverted branch or this is something unrelated.

**Comment by wrooot** [comment]
@akrherz any ideas?

**Comment by akrherz** [comment]
`checkcode.checkstyle` appears to be failing for some unknown reason

**Comment by wrooot** [comment]
Yeah, something went wrong with that import fix. When i first tried to merge it,  it complained about every file in the source. Speedy, maybe you can start it fresh? Or i can apply it manually in a new PR tomorrow.

**Comment by speedy01** [comment]
odd..I'll fix it up...

**Pull request closed without merging**
