### PR TITLE
SPARK-1822 - Add additional default properties to control GUI settings

### PR DESCRIPTION
**Pull request by BittyByte**
The following additional settings in the _default.properties_ file are now available:

- HIDE_LOGIN_AS_INVISIBLE
- DISABLE_PREFERENCES_MENU_ITEM
- MAINT_FILESPEC
- DISABLE_PRESENCE_STATUS_CHANGE
- DISABLE_BROADCAST_MENU_ITEM
- DISABLE_AVATAR_TAB
- DISABLE_PLUGINS_MENU_ITEM

### CODE REVIEW

**Comment by BittyByte** [comment]
Hi Wroot,
I submitted PR #236 and there seem to be no conflicts this time. Also, I replaced DISABLE_PRESENCE_STATUS_BAR and DISABLE_STATUS_IN_SYSTRAY with DISABLE_PRESENCE_STATUS_CHANGE so that there is only ONE setting needed. I figured that if a Sysadmin doesn't want his users to change their presence status in the status bar, then he probably doesn't want them changing it in the system tray either.

**Comment by BittyByte** [comment]
Hi Wroot,
You're welcome and thanks again for all your help. If I have any further questions, ideas, or issues, would you have a more direct method that I may use to contact you?

**Comment by BittyByte** [comment]
Hi Wroot,


You're welcome and thanks again for all your help. If I have any further questions, ideas, or issues, would you have a more direct method that I may use to contact you? Email or PM, etc?

 

 

Regards,

 

Michael

**Comment by wrooot** [comment]
I'm still not receiving messages from older PRs (though it works for new ones). You can contact me via PM in the forums ;)

**Comment by akrherz** [comment]
Hi wrooot, this is a test comment for you

**Comment by wrooot** [comment]
Github said my email was in the blacklist on the server that sends comments notifications (because it bounced back once during the DNS DDoS). They have now removed it from blacklist. Need another comment test here :)

**Comment by BittyByte** [comment]
Testing, 1,2,3...

**Comment by wrooot** [comment]
Got it, thanks. Great! Everything is back to normal.

**Comment by BittyByte** [comment]
Wonderful! Enjoy the rest of your day.

**Comment by BittyByte** [comment]
Wonderful!

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by wrooot** [comment]
ok :)

**Comment by BittyByte** [comment]
Hi Wroot,
I'd like to add even more settings to default.properties file. Should I just re-open ticket SPARK-1822 or would you assign a new one to me?

**Comment by BittyByte** [comment]
Hi Wroot,
I'd like to add even more settings to default.properties file. Should I just re-open ticket SPARK-1822 or would you assign a new one to me?

 

Thanks,

 

Michael

**Comment by wrooot** [comment]
You can re-open that ticket. Just update the description and add new options. Then mention this ticket in the title of a new PR. Btw, what options you are going to add?

P.S. for some reason you add two replies here. One via Github and the other one is via email i guess.

**Comment by BittyByte** [comment]
OK, thanks. I'll do that. Here are the new options which I noticed some people asked for on the community forum:

_# If true, disable the option to transfer files_
**DISABLE_FILE_XFER = false**

_# If true, disable the option to remove contacts and groups in roster_
**DISABLE_REMOVALS = false**

_# If true, disable the option to rename contacts and groups in roster_
**DISABLE_RENAMES = false**

_# If true, disable the options to move and copy contacts_
**DISABLE_MOVE_AND_COPY = false**

_# If true, disable the option to edit the profile_
**DISABLE_EDIT_PROFILE = false**

_# If true, disable the "View notes" option under "Actions"_
**DISABLE_VIEW_NOTES = false**

_# If true, disable the "View task list" option under "Actions"_
**DISABLE_VIEW_TASK_LIST = false**

Sorry about the 2 replies. I couldn't figure out how to PM you (feature was removed from GitHub), so I just tried to use email and GitHub forum reply to contact you...

**Comment by wrooot** [comment]
I never was aware about a PM option here :D This question is ok to ask publicly, but if you really need to PM me in future, you can do this in the forums (just go to my profile there and press the Message button). If you want i can give you my email via PM in the forums (just don't want to give it out here in public).

As for the changes. File Transfer can already be disabled via Client Control plugin. Well, one may want to do all the restrictions in one place so probably won't hurt to have it in default.properties. Just make sure not to miss context menu option like here https://issues.igniterealtime.org/browse/SPARK-1592

Same with the avatar\edit profile (can be disabled in Client Control). Make sure to catch the right click on existing avatar - https://issues.igniterealtime.org/browse/SPARK-1516 Maybe you can even fix this for Client Control case.

**Comment by BittyByte** [comment]
Yes, I read that GitHub did away with private messaging back in April 2012 - "Today we're removing two features. They've been gathering dust for a while and it's time to throw them out : Fork Queue & Private Messaging".

I found the Message button on the igniterealtime forums so I'll use that in the future if I need to PM.

**Comment by BittyByte** [comment]
I'm aware that the Client Control plugin can be used for disabling File Transfer and Avatar/Edit profile. However, it's either an "all or nothing" king of control and doesn't allow an admin to specify individual groups or users.

**Comment by wrooot** [comment]
Yeah, that's true. Btw, Client Control also removes the Send Screenshot button when File transfer is disabled. Though this is not exactly a file transfer, but kind of is also :) Just letting you know.

**Comment by BittyByte** [comment]
If there is a need to remove the "Send Screenshot" button, I can try to add that option as well.

**Comment by BittyByte** [comment]
By the way, I originally intended to remove the OTR button as well as requested on the forums. However, I noticed it's actually controlled by a plugin whose settings are in the Preferences menu. So it can easily be disabled within that menu (and then disable the Preferences menu of course) or just don't distribute the otrplug.jar to the user.

**Comment by wrooot** [comment]
Yes, there is also an option to blacklist plugins in default.properties.

**Comment by BittyByte** [comment]
That's probably the _best_ solution to disabling OTR. In fact, that how I have it set up at one of my clients' sites. I don't know how I forgot to mention it! Anyway, now you got me thinking about the "Send Screenshot" button - I'll look into it later today. Thanks again for all your help.

**Comment by BittyByte** [comment]
Hi Wroot,
I've been a busy beaver. I just added the **DISABLE_SCREENSHOTS** option. I will create a new PR for it.

**Comment by wrooot** [comment]
Ok

**Pull request merged**
